import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "./RuntimeComponents/AppSidebar";
import { ProjectSidebar } from "./RuntimeComponents/ProjectSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden w-screen `}
      >
        <SidebarProvider id="1" className="h-screen ">
          {/* left siderbar */}
           <AppSidebar />

           {/* triger for mobile view */}
           <span className="sm:block lg:hidden">
           <SidebarTrigger  />
           </span>


    
      {/* main Content */}
      
      <main className="w-full ">
        {children}
      </main>
        <ProjectSidebar/>
    </SidebarProvider>
      </body>
    </html>
  );
}
